import { Config, StateWithForms } from 'src/typings';

type TestState = {
    field1: {
        nestedfield1: string,
        nestedField2: number,
    }[],
};

export const arrayConfig: Config<TestState> = {
    name: 'arrayForm',
    fields: {
        field1: {
            multiple: true,
            default: {
                nestedField1: {
                    value: 'value',
                    default: 'default value',
                },
                nestedField2: {
                    type: 'number',
                    value: 18,
                },
            },
            fields: [{
                nestedField1: {},
                nestedField2: {},
            }],
        },
    },
};

export const arrayState: StateWithForms =  {
    arrayForm: {
        action: '',
        name: 'arrayForm',
        method: 'POST',
        fields: {
            field1: {
                key: 'field1',
                path: 'field1',
                focused: false,
                touched: false,
                changed: false,
                showErrors: false,
                extra: {},
                fieldType: 'ARRAY',
                default: {
                    nestedField1: {
                        key: 'nestedField1',
                        path: 'field1.nestedField1',
                        focused: false,
                        touched: false,
                        changed: false,
                        showErrors: false,
                        extra: {},
                        fieldType: 'SIMPLE',
                        value: 'value',
                        default: 'default value',
                        initial: 'value',
                        rules: '',
                        name: 'nestedField1',
                        id: 'nested-field-1',
                        type: 'text',
                        label: 'Nested Field 1',
                        placeholder: 'Nested Field 1',
                        disabled: false,
                        autoFocus: false,
                        autoComplete: 'nestedField1',
                        errors: [],
                    },
                    nestedField2: {
                        key: 'nestedField2',
                        path: 'field1.nestedField2',
                        focused: false,
                        touched: false,
                        changed: false,
                        showErrors: false,
                        extra: {},
                        fieldType: 'SIMPLE',
                        value: 18,
                        default: '',
                        initial: 18,
                        rules: '',
                        name: 'nestedField2',
                        id: 'nested-field-2',
                        type: 'number',
                        label: 'Nested Field 2',
                        placeholder: 'Nested Field 2',
                        disabled: false,
                        autoFocus: false,
                        autoComplete: 'nestedField2',
                        errors: [],
                    },
                },
                fields: [
                    {
                        nestedField1: {
                            key: '[0].nestedField1',
                            path: 'field1[0].nestedField1',
                            focused: false,
                            touched: false,
                            changed: false,
                            showErrors: false,
                            extra: {},
                            fieldType: 'SIMPLE',
                            value: 'value',
                            default: 'default value',
                            initial: 'value',
                            rules: '',
                            name: 'field1[][nestedField1]',
                            id: 'nested-field-1-0',
                            type: 'text',
                            label: 'Nested Field 1',
                            placeholder: 'Nested Field 1',
                            disabled: false,
                            autoFocus: false,
                            autoComplete: 'nestedField1',
                            errors: [],
                        },
                        nestedField2: {
                            key: '[0].nestedField2',
                            path: 'field1[0].nestedField2',
                            focused: false,
                            touched: false,
                            changed: false,
                            showErrors: false,
                            extra: {},
                            fieldType: 'SIMPLE',
                            value: 18,
                            default: '',
                            initial: 18,
                            rules: '',
                            name: 'field1[][nestedField2]',
                            id: 'nested-field-2-0',
                            type: 'number',
                            label: 'Nested Field 2',
                            placeholder: 'Nested Field 2',
                            disabled: false,
                            autoFocus: false,
                            autoComplete: 'nestedField2',
                            errors: [],
                        },
                    },
                ],
            },
        },
        isAsync: false,
        extra: {},
    },
};
